spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "my client id"
            client-secret: "my client secret"
            scope:
              - email
              - profile