spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth-test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mac32pro
    driver-class-name: com.mysql.cj.jdbc.Driver
